"""Demo opportunities, kept in one place and separate from the API/UI logic
so they can be swapped for a real data source (a partner feed, a form
pipeline, etc.) without touching any routes.

This mirrors js/data.js in the frontend so the two stay in sync while you
still have both a static demo and a backend-powered version.
"""

from datetime import date

ORGS = {
    "Internship": "Demo Tech Co.",
    "Scholarship": "Demo Education Fund",
    "Hackathon": "Demo Innovation Labs",
    "MUN": "Demo MUN Society",
    "Competition": "Demo Challenge Board",
    "Event": "Demo Student Network",
    "Workshop": "Demo Learning Hub",
    "Volunteering": "Demo Community Trust",
}

# (category, title, location, type, deadline, tags, description, eligibility)
RAW = [
    ("Internship", "Software Engineering Intern", "Remote", "Online", "2026-10-25",
     "Software Engineering,Python,Paid",
     "Work on real product features with a mentor and ship code in your first month.",
     "University students, year 2+"),
    ("Internship", "Data Science Intern", "Karachi, Pakistan", "Hybrid", "2026-11-05",
     "AI,Python,Paid",
     "Clean datasets, build dashboards and try ML models on live business questions.",
     "Students with basic Python/stats"),
    ("Internship", "UI/UX Design Intern", "Remote", "Online", "2026-11-12",
     "Design,Figma,Unpaid",
     "Design and test app flows alongside a small product team.",
     "Any student with a portfolio"),
    ("Internship", "Finance & Analytics Intern", "Lahore, Pakistan", "In-person", "2026-10-30",
     "Finance,Excel,Paid",
     "Support budgeting, reporting and market research for a growing startup.",
     "Business/economics students"),
    ("Internship", "Startup Growth Intern", "Remote", "Online", "2026-12-01",
     "Entrepreneurship,Marketing,Paid",
     "Test growth ideas and learn how early-stage startups find customers.",
     "Undergraduates"),
    ("Scholarship", "Global Undergraduate Scholarship", "Multiple Countries", "In-person", "2026-11-20",
     "Fully Funded,International Relations",
     "Covers tuition, housing and travel for outstanding undergraduate applicants.",
     "Undergraduate students"),
    ("Scholarship", "STEM Future Leaders Award", "United Kingdom", "In-person", "2026-12-10",
     "Software Engineering,AI,Tuition",
     "Partial tuition support for women and gender-diverse students in STEM.",
     "STEM Master's applicants"),
    ("Scholarship", "Community Impact Grant", "Pakistan", "Online", "2026-11-15",
     "Volunteering,Tuition",
     "Financial support for students who lead community service projects.",
     "High-school graduates"),
    ("Scholarship", "Design Excellence Scholarship", "Germany", "In-person", "2027-01-10",
     "Design,Fully Funded",
     "Fully funded design program with monthly stipend.",
     "Portfolio required"),
    ("Scholarship", "Business Leaders Fellowship", "Canada", "Hybrid", "2026-12-20",
     "Finance,Entrepreneurship,Tuition",
     "Tuition waiver plus mentorship from business leaders.",
     "Business undergraduates"),
    ("Hackathon", "Global AI Hackathon 2026", "Online", "Online", "2026-10-18",
     "AI,Software Engineering,Beginner Friendly",
     "Build innovative AI solutions and compete with students from around the world.",
     "Any student, teams of 2-4"),
    ("Hackathon", "Campus Green Tech Jam", "Karachi, Pakistan", "In-person", "2026-10-22",
     "Software Engineering,Sustainability",
     "A 24-hour build sprint on climate and campus sustainability tools.",
     "University students"),
    ("Hackathon", "FinTech Hack Weekend", "Remote", "Online", "2026-11-08",
     "Finance,Software Engineering",
     "Prototype payment and budgeting tools for young people.",
     "Teams of 3-5"),
    ("Hackathon", "Beginner Build Night", "Islamabad, Pakistan", "In-person", "2026-11-01",
     "Beginner Friendly,Design",
     "A friendly first hackathon with mentors and starter kits.",
     "No experience needed"),
    ("MUN", "Karachi Youth MUN 2026", "Karachi, Pakistan", "In-person", "2026-11-10",
     "International Relations,Debate",
     "Three-day conference with UNSC, WHO and Crisis committees.",
     "Grades 9-12 and university"),
    ("MUN", "Virtual Global MUN", "Online", "Online", "2026-10-28",
     "International Relations,Public Speaking",
     "Join delegates worldwide from your laptop; beginner committees available.",
     "Ages 15+"),
    ("MUN", "Lahore Model UN Summit", "Lahore, Pakistan", "In-person", "2026-12-05",
     "International Relations,Debate",
     "Debate global policy and network with experienced delegates.",
     "University students"),
    ("Competition", "National Coding Challenge", "Online", "Online", "2026-10-31",
     "Software Engineering,Coding",
     "Solve algorithmic problems in a timed contest with cash prizes.",
     "Undergraduates"),
    ("Competition", "Business Case Cup", "Karachi, Pakistan", "In-person", "2026-11-18",
     "Finance,Entrepreneurship,Business",
     "Pitch solutions to a real-style business case to a judging panel.",
     "Teams of 3-4"),
    ("Competition", "Youth Essay Prize", "Online", "Online", "2026-12-15",
     "Writing,International Relations",
     "Write on the theme 'The World in 2050' for publication.",
     "Ages 16-25"),
    ("Competition", "Math Olympiad Open", "Online", "Online", "2026-11-25",
     "Mathematics,Science",
     "Problem-solving contest with rounds for all skill levels.",
     "Students under 25"),
    ("Event", "Student Career Fair", "Karachi, Pakistan", "In-person", "2026-10-24",
     "Career,Networking",
     "Meet employers, get CV feedback and explore graduate roles.",
     "Open to all students"),
    ("Event", "Future of AI Student Conference", "Online", "Online", "2026-11-03",
     "AI,Software Engineering",
     "Talks and panels on AI careers and research.",
     "Free registration"),
    ("Event", "Startup Networking Mixer", "Lahore, Pakistan", "In-person", "2026-10-29",
     "Entrepreneurship,Networking",
     "Meet founders and find teammates for your next project.",
     "University students"),
    ("Workshop", "Python for Beginners", "Online", "Online", "2026-10-21",
     "Python,Software Engineering,Beginner Friendly",
     "A hands-on 4-week workshop to write your first programs.",
     "No experience needed"),
    ("Workshop", "Design Thinking Lab", "Islamabad, Pakistan", "In-person", "2026-11-07",
     "Design,Entrepreneurship",
     "Learn to define problems and prototype ideas quickly.",
     "Any student"),
    ("Workshop", "Public Speaking Bootcamp", "Online", "Online", "2026-11-14",
     "Public Speaking,Career",
     "Practice pitching, storytelling and confident delivery.",
     "Ages 16+"),
    ("Workshop", "Intro to Machine Learning", "Online", "Online", "2026-12-02",
     "AI,Python",
     "Train your first model with guided notebooks.",
     "Basic Python helpful"),
    ("Volunteering", "Teach a Weekend Class", "Karachi, Pakistan", "In-person", "2026-11-06",
     "Volunteering,Education",
     "Tutor school students in maths and English on weekends.",
     "Ages 17+"),
    ("Volunteering", "Remote Digital Skills Mentor", "Remote", "Online", "2026-12-12",
     "Volunteering,Software Engineering",
     "Mentor learners online on digital literacy topics.",
     "University students"),
    ("Volunteering", "Community Clean-Up Drive", "Lahore, Pakistan", "In-person", "2026-10-26",
     "Volunteering,Sustainability",
     "Join a team cleaning parks and green spaces.",
     "Open to all"),
]


def seed_opportunities(db, Opportunity):
    """Insert the demo opportunities if the table is empty. Safe to call on
    every startup — it's a no-op once data exists."""
    if Opportunity.query.first():
        return

    for category, title, location, type_, deadline, tags, description, eligibility in RAW:
        db.session.add(
            Opportunity(
                category=category,
                title=title,
                organization=ORGS[category],
                location=location,
                type=type_,
                deadline=date.fromisoformat(deadline),
                description=description,
                eligibility=eligibility,
                tags=tags.split(","),
                is_demo=True,
            )
        )
    db.session.commit()
